# Generated by Django 3.2.8 on 2021-10-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20211023_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
