# Generated by Django 4.0 on 2021-12-11 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('allowed_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_boards', to='kanban.user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_boards', to='kanban.user')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('BACKLOG', 'Freshman'), ('TODO', 'To Do'), ('INPROGRESS', 'In Progress'), ('DONE', 'Done'), ('CLOSED', 'Closed')], default='BACKLOG', max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='assigned_tasks', to='kanban.user')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='kanban.board')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='kanban.user')),
                ('reviewer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='review_tasks', to='kanban.user')),
            ],
        ),
    ]
