# Generated by Django 4.0 on 2021-12-12 00:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_board_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='allowed_users',
        ),
        migrations.AddField(
            model_name='board',
            name='allowed_users',
            field=models.ManyToManyField(related_name='allowed_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
