# Generated by Django 4.0 on 2021-12-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_remove_board_allowed_users_board_allowed_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='todo', max_length=16),
        ),
    ]
