# Generated by Django 4.0 on 2021-12-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
